project:
  type: website
  output-dir: docs

website:
  title: "Daniel Coker"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Viz
        menu:
          - text: "Himalayas"
            href: Himalayas.html
          - text: "Water Insecurity"
            href: Water Security.html
          - text: "Obama Tweet"
            href: Obama Tweet.html
          - text: "Chick Permutation"
            href: Chick Permutation.html
          - text: "Data Science Ethics"
            href: Data Science Ethics.html
          - text: "Standford Open Policing Project Regression"
            href: Standford Open Policing Project.html

format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual
